const config = {
  type: 'scatter',
  title: 'Relationship Between Age and Maximum Heart Rate by Gender',
  xAxis: {
    title: 'Age'
  },
  yAxis: {
    title: 'Maximum Heart Rate (thalachh)'
  },
  series: [{
    name: 'Men',
    xField: 'age',
    yField: 'thalachh',
    data: [{
      age: 63,
      gender: 1,
      thalachh: 150
    }, {
      age: 37,
      gender: 1,
      thalachh: 187
    }, {
      age: 56,
      gender: 1,
      thalachh: 178
    }, {
      age: 57,
      gender: 1,
      thalachh: 148
    }, {
      age: 44,
      gender: 1,
      thalachh: 173
    }, {
      age: 52,
      gender: 1,
      thalachh: 162
    }, {
      age: 57,
      gender: 1,
      thalachh: 174
    }, {
      age: 54,
      gender: 1,
      thalachh: 160
    }, {
      age: 49,
      gender: 1,
      thalachh: 171
    }, {
      age: 64,
      gender: 1,
      thalachh: 144
    }, {
      age: 43,
      gender: 1,
      thalachh: 171
    }, {
      age: 59,
      gender: 1,
      thalachh: 161
    }, {
      age: 44,
      gender: 1,
      thalachh: 179
    }, {
      age: 42,
      gender: 1,
      thalachh: 178
    }, {
      age: 61,
      gender: 1,
      thalachh: 137
    }, {
      age: 40,
      gender: 1,
      thalachh: 178
    }, {
      age: 59,
      gender: 1,
      thalachh: 157
    }, {
      age: 51,
      gender: 1,
      thalachh: 123
    }, {
      age: 53,
      gender: 1,
      thalachh: 152
    }, {
      age: 65,
      gender: 1,
      thalachh: 140
    }, {
      age: 44,
      gender: 1,
      thalachh: 188
    }, {
      age: 54,
      gender: 1,
      thalachh: 152
    }, {
      age: 48,
      gender: 1,
      thalachh: 180
    }, {
      age: 45,
      gender: 1,
      thalachh: 148
    }, {
      age: 39,
      gender: 1,
      thalachh: 182
    }, {
      age: 52,
      gender: 1,
      thalachh: 172
    }, {
      age: 44,
      gender: 1,
      thalachh: 180
    }, {
      age: 47,
      gender: 1,
      thalachh: 156
    }, {
      age: 66,
      gender: 1,
      thalachh: 151
    }, {
      age: 62,
      gender: 1,
      thalachh: 146
    }, {
      age: 52,
      gender: 1,
      thalachh: 158
    }, {
      age: 48,
      gender: 1,
      thalachh: 186
    }, {
      age: 45,
      gender: 1,
      thalachh: 148
    }, {
      age: 34,
      gender: 1,
      thalachh: 174
    }, {
      age: 54,
      gender: 1,
      thalachh: 156
    }, {
      age: 52,
      gender: 1,
      thalachh: 190
    }, {
      age: 41,
      gender: 1,
      thalachh: 132
    }, {
      age: 58,
      gender: 1,
      thalachh: 165
    }, {
      age: 51,
      gender: 1,
      thalachh: 143
    }, {
      age: 44,
      gender: 1,
      thalachh: 170
    }, {
      age: 54,
      gender: 1,
      thalachh: 147
    }, {
      age: 51,
      gender: 1,
      thalachh: 154
    }, {
      age: 29,
      gender: 1,
      thalachh: 202
    }, {
      age: 51,
      gender: 1,
      thalachh: 186
    }, {
      age: 51,
      gender: 1,
      thalachh: 166
    }, {
      age: 59,
      gender: 1,
      thalachh: 164
    }, {
      age: 52,
      gender: 1,
      thalachh: 184
    }, {
      age: 58,
      gender: 1,
      thalachh: 154
    }, {
      age: 41,
      gender: 1,
      thalachh: 182
    }, {
      age: 38,
      gender: 1,
      thalachh: 173
    }, {
      age: 38,
      gender: 1,
      thalachh: 173
    }, {
      age: 67,
      gender: 1,
      thalachh: 108
    }, {
      age: 67,
      gender: 1,
      thalachh: 129
    }, {
      age: 63,
      gender: 1,
      thalachh: 147
    }, {
      age: 53,
      gender: 1,
      thalachh: 155
    }, {
      age: 56,
      gender: 1,
      thalachh: 142
    }, {
      age: 48,
      gender: 1,
      thalachh: 168
    }, {
      age: 58,
      gender: 1,
      thalachh: 160
    }, {
      age: 58,
      gender: 1,
      thalachh: 173
    }, {
      age: 60,
      gender: 1,
      thalachh: 132
    }, {
      age: 40,
      gender: 1,
      thalachh: 114
    }, {
      age: 60,
      gender: 1,
      thalachh: 160
    }, {
      age: 64,
      gender: 1,
      thalachh: 158
    }, {
      age: 43,
      gender: 1,
      thalachh: 120
    }, {
      age: 57,
      gender: 1,
      thalachh: 168
    }, {
      age: 55,
      gender: 1,
      thalachh: 155
    }, {
      age: 41,
      gender: 1,
      thalachh: 168
    }, {
      age: 56,
      gender: 1,
      thalachh: 162
    }, {
      age: 59,
      gender: 1,
      thalachh: 182
    }, {
      age: 44,
      gender: 1,
      thalachh: 161
    }, {
      age: 41,
      gender: 1,
      thalachh: 181
    }, {
      age: 60,
      gender: 1,
      thalachh: 103
    }, {
      age: 45,
      gender: 1,
      thalachh: 168
    }, {
      age: 42,
      gender: 1,
      thalachh: 120
    }, {
      age: 42,
      gender: 1,
      thalachh: 125
    }, {
      age: 64,
      gender: 1,
      thalachh: 128
    }, {
      age: 62,
      gender: 1,
      thalachh: 138
    }, {
      age: 60,
      gender: 1,
      thalachh: 126
    }, {
      age: 44,
      gender: 1,
      thalachh: 144
    }, {
      age: 50,
      gender: 1,
      thalachh: 163
    }, {
      age: 38,
      gender: 1,
      thalachh: 173
    }, {
      age: 63,
      gender: 1,
      thalachh: 132
    }, {
      age: 56,
      gender: 1,
      thalachh: 108
    }, {
      age: 61,
      gender: 1,
      thalachh: 146
    }, {
      age: 50,
      gender: 1,
      thalachh: 163
    }, {
      age: 43,
      gender: 1,
      thalachh: 147
    }, {
      age: 55,
      gender: 1,
      thalachh: 113
    }, {
      age: 60,
      gender: 1,
      thalachh: 125
    }, {
      age: 56,
      gender: 1,
      thalachh: 137
    }, {
      age: 50,
      gender: 1,
      thalachh: 186
    }, {
      age: 68,
      gender: 1,
      thalachh: 120
    }, {
      age: 36,
      gender: 1,
      thalachh: 112
    }, {
      age: 39,
      gender: 1,
      thalachh: 118
    }, {
      age: 42,
      gender: 1,
      thalachh: 146
    }, {
      age: 66,
      gender: 1,
      thalachh: 119
    }, {
      age: 49,
      gender: 1,
      thalachh: 126
    }, {
      age: 38,
      gender: 1,
      thalachh: 145
    }, {
      age: 40,
      gender: 1,
      thalachh: 126
    }, {
      age: 69,
      gender: 1,
      thalachh: 111
    }, {
      age: 67,
      gender: 1,
      thalachh: 114
    }, {
      age: 78,
      gender: 1,
      thalachh: 120
    }, {
      age: 69,
      gender: 1,
      thalachh: 115
    }, {
      age: 63,
      gender: 1,
      thalachh: 150
    }, {
      age: 73,
      gender: 1,
      thalachh: 145
    }]
  }, {
    name: 'Women',
    xField: 'age',
    yField: 'thalachh',
    data: [{
      age: 41,
      gender: 0,
      thalachh: 172
    }, {
      age: 57,
      gender: 0,
      thalachh: 163
    }, {
      age: 56,
      gender: 0,
      thalachh: 153
    }, {
      age: 48,
      gender: 0,
      thalachh: 139
    }, {
      age: 58,
      gender: 0,
      thalachh: 162
    }, {
      age: 50,
      gender: 0,
      thalachh: 158
    }, {
      age: 58,
      gender: 0,
      thalachh: 172
    }, {
      age: 66,
      gender: 0,
      thalachh: 114
    }, {
      age: 69,
      gender: 0,
      thalachh: 151
    }, {
      age: 71,
      gender: 0,
      thalachh: 162
    }, {
      age: 65,
      gender: 0,
      thalachh: 157
    }, {
      age: 41,
      gender: 0,
      thalachh: 168
    }, {
      age: 46,
      gender: 0,
      thalachh: 160
    }, {
      age: 54,
      gender: 0,
      thalachh: 170
    }, {
      age: 65,
      gender: 0,
      thalachh: 148
    }, {
      age: 65,
      gender: 0,
      thalachh: 151
    }, {
      age: 51,
      gender: 0,
      thalachh: 142
    }, {
      age: 53,
      gender: 0,
      thalachh: 143
    }, {
      age: 53,
      gender: 0,
      thalachh: 115
    }, {
      age: 53,
      gender: 0,
      thalachh: 160
    }, {
      age: 51,
      gender: 0,
      thalachh: 149
    }, {
      age: 44,
      gender: 0,
      thalachh: 175
    }, {
      age: 63,
      gender: 0,
      thalachh: 172
    }, {
      age: 57,
      gender: 0,
      thalachh: 159
    }, {
      age: 71,
      gender: 0,
      thalachh: 130
    }, {
      age: 35,
      gender: 0,
      thalachh: 182
    }, {
      age: 45,
      gender: 0,
      thalachh: 175
    }, {
      age: 62,
      gender: 0,
      thalachh: 163
    }, {
      age: 43,
      gender: 0,
      thalachh: 165
    }, {
      age: 55,
      gender: 0,
      thalachh: 161
    }, {
      age: 60,
      gender: 0,
      thalachh: 160
    }, {
      age: 42,
      gender: 0,
      thalachh: 122
    }, {
      age: 67,
      gender: 0,
      thalachh: 160
    }, {
      age: 54,
      gender: 0,
      thalachh: 158
    }, {
      age: 58,
      gender: 0,
      thalachh: 122
    }, {
      age: 54,
      gender: 0,
      thalachh: 159
    }, {
      age: 45,
      gender: 0,
      thalachh: 138
    }, {
      age: 62,
      gender: 0,
      thalachh: 160
    }, {
      age: 63,
      gender: 0,
      thalachh: 179
    }, {
      age: 68,
      gender: 0,
      thalachh: 115
    }, {
      age: 45,
      gender: 0,
      thalachh: 152
    }, {
      age: 50,
      gender: 0,
      thalachh: 162
    }, {
      age: 50,
      gender: 0,
      thalachh: 159
    }, {
      age: 64,
      gender: 0,
      thalachh: 154
    }, {
      age: 64,
      gender: 0,
      thalachh: 133
    }, {
      age: 37,
      gender: 0,
      thalachh: 170
    }, {
      age: 46,
      gender: 0,
      thalachh: 172
    }, {
      age: 46,
      gender: 0,
      thalachh: 152
    }, {
      age: 64,
      gender: 0,
      thalachh: 122
    }, {
      age: 41,
      gender: 0,
      thalachh: 172
    }, {
      age: 54,
      gender: 0,
      thalachh: 167
    }, {
      age: 39,
      gender: 0,
      thalachh: 179
    }, {
      age: 34,
      gender: 0,
      thalachh: 192
    }, {
      age: 67,
      gender: 0,
      thalachh: 172
    }, {
      age: 52,
      gender: 0,
      thalachh: 169
    }, {
      age: 74,
      gender: 0,
      thalachh: 121
    }, {
      age: 54,
      gender: 0,
      thalachh: 163
    }, {
      age: 49,
      gender: 0,
      thalachh: 162
    }, {
      age: 41,
      gender: 0,
      thalachh: 163
    }, {
      age: 49,
      gender: 0,
      thalachh: 163
    }, {
      age: 60,
      gender: 0,
      thalachh: 96
    }, {
      age: 51,
      gender: 0,
      thalachh: 157
    }, {
      age: 42,
      gender: 0,
      thalachh: 173
    }, {
      age: 67,
      gender: 0,
      thalachh: 142
    }, {
      age: 76,
      gender: 0,
      thalachh: 116
    }, {
      age: 44,
      gender: 0,
      thalachh: 149
    }, {
      age: 60,
      gender: 0,
      thalachh: 171
    }, {
      age: 71,
      gender: 0,
      thalachh: 125
    }, {
      age: 66,
      gender: 0,
      thalachh: 152
    }, {
      age: 39,
      gender: 0,
      thalachh: 152
    }, {
      age: 58,
      gender: 0,
      thalachh: 131
    }, {
      age: 55,
      gender: 0,
      thalachh: 166
    }, {
      age: 62,
      gender: 0,
      thalachh: 160
    }, {
      age: 65,
      gender: 0,
      thalachh: 114
    }, {
      age: 61,
      gender: 0,
      thalachh: 169
    }, {
      age: 51,
      gender: 0,
      thalachh: 142
    }, {
      age: 62,
      gender: 0,
      thalachh: 106
    }, {
      age: 62,
      gender: 0,
      thalachh: 154
    }, {
      age: 66,
      gender: 0,
      thalachh: 165
    }, {
      age: 63,
      gender: 0,
      thalachh: 169
    }, {
      age: 55,
      gender: 0,
      thalachh: 117
    }, {
      age: 58,
      gender: 0,
      thalachh: 146
    }, {
      age: 63,
      gender: 0,
      thalachh: 136
    }, {
      age: 57,
      gender: 0,
      thalachh: 123
    }, {
      age: 57,
      gender: 0,
      thalachh: 174
    }]
  }]
};
let chart;
function init() {
  console.log('RealChart v' + RealChart.getVersion());
  RealChart.setLogging(true);
  chart = RealChart.createChart(document, 'realchart', config);
}