name: Copy Folder to realchart-demo

on:
  push:
    branches:
      - release/v1.1.0
    paths:
      - 'fiddle/**'

jobs:
  copy-folder:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source repository
      uses: actions/checkout@v2

    - name: Copy folder to destination repository
      env:
        TOKEN: ${{ secrets.REAL_CHART_FIDDLE_TOKEN }}
      run: |
        git config --global user.email "dltlghkd930217@gmail.com"
        git config --global user.name "dltlghkd930217"
        
        git clone https://x-access-token:$TOKEN@github.com/realgrid/realchart-demo.git
        cp -r fiddle/* realchart-demo/
       # 변경 사항이 있는지 확인
        if [[ $(git status --porcelain) ]]; then
            # 변경 사항이 있을 때만 커밋 실행
            git add .
            git commit -m "Copied folder for fiddle demo"
            git push
        else
            # 변경 사항이 없을 때는 메시지만 출력
            echo "No changes to commit."
        fi
