name: Copy Folder to realchart-demo

on:
  push:
    paths:
      - 'fiddle/**'

jobs:
  copy-folder:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source repository
      uses: actions/checkout@v2

    - name: Copy to realchart-demo
      id: check_changes
      env:
        TOKEN: ${{ secrets.REAL_CHART_FIDDLE_TOKEN }}
      run: |
        git config --global user.email "dltlghkd930217@gmail.com"
        git config --global user.name "dltlghkd930217"
        
        git clone https://x-access-token:$TOKEN@github.com/realgrid/realchart-demo.git
        cp -r fiddle/* realchart-demo/
        cd realchart-demo
        echo ::set-output name=changes::$(git status --porcelain)

    - name: Push to realchart-demo
      if: ${{ steps.check_changes.outputs.changes != '' }}
      run: |
        git add .
        git commit -m "Copied folder for fiddle demo"
        git push
