name: Copy Folder to realchart-demo

on:
  workflow_dispatch:
  push:
    paths:
      - 'fiddle/**'

jobs:
  copy-folder:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source repository
      uses: actions/checkout@v2

    - name: Copy to realchart-demo
      id: check_changes
      run: |
        git config user.name "benny-yoo"
        git config user.email "benny@wooritech.com"
        
        git clone https://github.com/realgrid/realchart-demo.git
        cp -r fiddle/* realchart-demo/
        cd realchart-demo
        echo ::set-output name=changes::$(git status --porcelain)

    - name: Push to realchart-demo
      uses: GuillaumeFalourd/git-commit-push@v1.3
      if: ${{ steps.check_changes.outputs.changes != '' }}
      with:
        target_branch: main
        remote_repository: https://github.com/realgrid/realchart-demo.git
        access_token: ${{secrets.REAL_CHART_FIDDLE_TOKEN}}
        commit_message: "Copied folder for fiddle demo"
        force: true
